### ISSUE TITLE
Service endpoint method as GET isn't accepted

### ISSUE THREAD

**Issue by KB-perByte** [NilashishC/ansible-creator-service#1]
We ran into the following error, while using `import fetch from 'node-fetch';`  in our backstage application.
Usage - 
```
...
    const requestOptions = {
        method: 'GET',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({ collection: 'testns.testorg' })
    };

    try {
        const response = await fetch('http://localhost:5000/init', requestOptions);

        if (!response.ok) {
            throw new Error('Failed to fetch data');
        }
 ...
```

Error - 
```
info: Running ansible collection create for testns.testorg
Error: TypeError: Request with GET/HEAD method cannot have body
    at new Request (/home/abc/Work/DevHub/backstage/node_modules/node-fetch/lib/index.js:1221:10)
    at /home/abc/Work/DevHub/backstage/node_modules/node-fetch/lib/index.js:1449:19
-------
    at NunjucksWorkflowRunner.execute (/home/abc/Work/DevHub/backstage/plugins/scaffolder-backend/src/scaffolder/tasks/NunjucksWorkflowRunner.ts:501:9)
    at TaskWorker.runOneTask (/home/abc/Work/DevHub/backstage/plugins/scaffolder-backend/src/scaffolder/tasks/TaskWorker.ts:176:26)
```
Sticking to the specific library as it is recommended by backstage docs, having a 3rd party library packed with the downstream RHDH image would be critical.
We could check, a POST request works in our case.

Regards.

**Comment by NilashishC** [comment]
Fixed.
